// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxWqg__7mTAh_WOueGScCaau91nIwkI7c',
    appId: '1:140313064277:android:be645a696297ae87ccf5dc',
    messagingSenderId: '140313064277',
    projectId: 'live-translate-app-ea909',
    storageBucket: 'live-translate-app-ea909.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJHbsCZzvvGfz3tnObb0kTsrVW2UzDuU4',
    appId: '1:140313064277:ios:11d05959c1427ca9ccf5dc',
    messagingSenderId: '140313064277',
    projectId: 'live-translate-app-ea909',
    storageBucket: 'live-translate-app-ea909.firebasestorage.app',
    iosBundleId: 'com.example.liveTranslateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkdOvNkMj_QAPsgPEZOvlzhg_D-U3AhUU',
    appId: '1:140313064277:web:4d29c2e9aeb71bccccf5dc',
    messagingSenderId: '140313064277',
    projectId: 'live-translate-app-ea909',
    authDomain: 'live-translate-app-ea909.firebaseapp.com',
    storageBucket: 'live-translate-app-ea909.firebasestorage.app',
    measurementId: 'G-8GYQG11E1K',
  );
}
